# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'optimistic panda'
tagline:          ''
description:      'devfoodblog by <a href="https://twitter.com/plasma147" target="_blank">@plasma147</a>.'
url:              http://plasma147.github.io
baseurl:          /

author:
  name:           'Andy Lee'
  url:            https://twitter.com/plasma147

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/plasma147/
